### PR TITLE
Populate the contributions.md file

### PR DESCRIPTION
**Pull request by gtvj**
Following on from the meeting this afternoon I've created a `contributions.md` file with headings for the sections we're going to populate. Just to recap, we've agreed to have populated the following sections before the meeting with JS on 2 October

- [x] populate 'Principles and Philosophy' section **Chris**
- [x] populate Guidelines, Commit messages, Guideline check list sections **Gwyn**
- [ ] populate Process and review process section **Matt**
- [x] populate Versioning section **Punal**
- [x] populate Contribution criteria section **Simon**

I hope the session today went OK for everyone. If anyone has any thoughts/concerns/suggestions then please add them to this PR (@'ing people as necessary) so that we've got everything captured.

### CODE REVIEW

**Comment by gtvj** [comment]
Hi @plembke-tna - I wasn't able to add you to the PR but once you've accepted the invitation I can. Just let me know.

**Comment by domjngo** [comment]
My contribution added :-)

**Comment by gtvj** [comment]
My contribution added 😃

**Comment by sdwilkes** [comment]
I've added the ' Contribution criteria'

**Review by domjngo — APPROVED** [review]

**Pull request merged**
